Repository mlr-org/mlr3book, pull requests merged in 2019-06, with the labels that each got.

#13 Add chapter about feature-selection
  bookdown/07-optimization.Rmd
  bookdown/98-appendix.Rmd
Labels: section: feature-selection

#16 WIP: added paradox vignette to the book
  bookdown/03-paradox.Rmd
Labels: WIP - work in progress, section: tuning

#11 Add a section in Introduction with a mlr->mlr3 lookup table
  .gitignore
  bookdown/01-mlr3-basics.Rmd
Labels: section: core
